### ISSUE TITLE
workshop maps nominations and rtv exclusions

### ISSUE THREAD

**Issue by Baxuriuks** [Silenci0/UMC#11]
I have a problem with played maps exclusions in nominate and rtv when using workshop maps.  However if using non-workshop maps then everything works perfect, they do get excluded as per configuration. 
Did anyone came across this kind of problem and maybe knows a solution for it?

**Comment by Silenci0** [comment]
UMC does not work with workshop maps currently and needs an update to fix it. It is being worked on, but progress is slow.

**Comment by Baxuriuks** [comment]
Oh, good to know it's been worked on. Will be looking forward for upcoming updates. Thank you for an answer.
