### ISSUE TITLE
Endvote bug? Map stays the same.

### ISSUE THREAD

**Issue by arestonelle** [Silenci0/UMC#13]
Hi Silenci! Thank you for supporting this plugin. I have an issue and i don't know how to solve it.

Endvote voting. People plays on XXX map. People choose map group, people choose map. Echo nextmap confirming, that next map will be "YYY", and after map ends there is again XXX map. Strange thing, that sometimes it's work normally. But often this issue happens. I dunno what to do. Debug log write all normally, that map changed to the choosen one. SM Erro Log clear. 

I use EndVote Tired Vote. 4 MapGroups including 6-8 maps. 1 Group with original maps and 3 with workshop maps. I try to remove {display} option, use voting without any options - helpless. 

Can you advise something? 

Best regards.

P.S. some people fix same problem with default or sm mapvoting by this cvars:
//mp_match_end_restart 0
//mp_match_end_changelevel 1
but they are was helpless in my problem.

**Comment by Silenci0** [comment]
Hello arestonelle,

Is this for CS:GO or another game? Also, did you make sure that other mapchooser plugins (including the default mapchooser plugins from Sourcemod) are disabled? It sounds to me that something is setting the next map after UMC does its endvote, especially if it is working part of the time.

**Comment by arestonelle** [comment]
Hi, thanks for your reply. Yeah, i'm pretty sure, that all plugins for map choosing instead of UMC+Plugins is disabled. This is totally strange, cuz if some plugin make endvote of umc inactive, why some part of the time it work properly and change map to choosen one...?

I think thta you dont need it, and it can not be helpfully, but there is a plugin list enabled on the server:

<details>
01 "CD Announcer" (2.9) by Fredd, gH0sTy, MOPO3KO
02 "Rotate server graphic banners" (0.3) by HiTmAnY
03 "SM Franug CSGO Sprays" (1.4.2) by Franc1sco Steam: franug, EMINEM and Invictus
04 "Adverstiments" (1.4.1) by Pheonix (˙·٠●Феникс●٠·˙)
05 "Extended Player Death Info" (1.0.0) by Phoenix (˙·٠●Феникс●٠·˙), Icons created Bastaz
06 "CS:GO Esl Admin ESP (mmcs.pro)" (2.8) by SAZONISCHE
07 "[UMC] Map Commands" (3.6.2) by Steell
08 "BlockingZones" (1.3) by Drumanid
09 "Weapon Skin" (2.3.9 PRIVATE) by Phoenix (˙·٠●Феникс●٠·˙)
10 "Quake Sounds v3" (3.5.6) by Spartan_C001(fork by Dragokas)
11 "Admin all spec" (1.0.2) by Dr!fter
12 "[CSS/CS:GO] AbNeR ResetScore" (1.5fix) by AbNeR_CSS
13 "Admin Menu" (0.7.7) by AlliedModders LLC
14 "CFGam1ng Weaponmenu" (1.0.0) by Invictus
15 "Basic Chat" (1.9.0.6276) by AlliedModders LLC
16 "[VIP] Features Manager" (1.0) by Pheonix (˙·٠●Феникс●٠·˙)
17 "[UMC] Rock The Vote" (3.6.2) by Steell
18 "Fun Votes" (1.9.0.6280) by AlliedModders LLC
19 "[VIP] Additional" (1.0.1) by Drumanid
20 "[VIP] Show Damage" (1.0.0) by R1KO
21 "[VIP] MuteGagSilence (+materialadmin)" (1.0) by R1KO
22 "[VIP] Bhop" (1.0.1) by KOROVKA
23 "[VIP] No Fall Damage" (1.0.1) by R1KO (skype: vova.andrienko1)
24 "[VIP] Client Spawn Hook Fix" (1.0) by CrazyHackGUT aka Kruzya
25 "[VIP] Defuser" (1.0.1) by R1KO & T1MOX4
26 "[VIP] Weapon Immunity" (1.0.0) by Phoenix (˙·٠●Феникс●٠·˙)
27 "[VIP] Core" (3.0 R) by R1KO
28 "[VIP] No Self Damage" (1.0.0) by R1KO (skype: vova.andrienko1)
29 "[VIP] ExoJumpBoots" (1.0) by R1KO
30 "[VIP] Покупка оружия команды" (1.2.3) by Planes
31 "[VIP] Healthshot" (1.0.1) by R1KO (skype: vova.andrienko1)
32 "[VIP] Kill Bonus" (1.0.0) by R1KO (skype: vova.andrienko1)
33 "[VIP] Extended Ammo" (1.10) by R1KO
34 "[VIP] Electro Effects" (1.0.3) by R1KO
35 "[VIP] Voice Sound Player" (28.09.2k17) by Danyas
36 "[VIP] Quick Defuse" (1.2) by R1KO
37 "[VIP] Endurance" (1.0.0) by R1KO (skype: vova.andrienko1)
38 "[VIP] Quick Hostage Rescue" (1.1) by R1KO
39 "[VIP] Damage Change" (1.2) by R1KO
40 "[VIP] COIN" (1.1.0) by Pheonix (˙·٠●Феникс●٠·˙) & R1KO
41 "vip/VIP_Extended_ammo_reloadfix.smx"
42 "vip/VIP_Parachute.smx"
43 "(VIP) Join Sound | Звук при входе" (1.0.2) by Drumanid
44 "[VIP] Tag" (1.1) by R1KO
45 "[VIP] CHAT (+scp)" (3.1.1) by R1KO
46 "[VIP] MKIT" (1.0.6) by Pheonix (edit Felya)
47 "[VIP] Shield" (1.3.1 [PUBLIC]) by Faya™ (DS: Faya™#8514)
48 "[VIP] Куб льда" (1.0) by Drimer
49 "[VIP] Evade (Уворот)" (1.0) by Miaka (Ice_Sochi) & R1KO
50 "[VIP] Nade Models (CS:GO)" (1.0.0) by R1KO
51 "[VIP] Anti Flash" (1.0.0) by R1KO
52 "[VIP] Tagrenade" (1.0.1) by R1KO (skype: vova.andrienko1)
53 "[VIP] Base Functions" (1.2) by R1KO (skype: vova.andrienko1)
54 "[VIP] Test" (1.0.3) by R1KO (skype: vova.andrienko1)
55 "[VIP] Spawn Effects" (1.2) by Mr.ToNik
56 "vip/VIP_Fastplant.smx"
57 "Player Commands" (1.9.0.6280) by AlliedModders LLC
58 "[UMC] End of Map Vote Warnings" (3.6.2) by Steell
59 "RoundEnd Speed" (1.0) by asdf
60 "InfoPlugins" by Invictus
61 "Admin Invictus" (2.1e) by Invictus
62 "Knife choice CORE - Выбор ножа ЯДРО" (2.8) by Phoenix - Феникс
63 "[Prime Natives] Tag" (1.0.0) by Someone
64 "Material Admin Checker" (0.7.7) by psychonic, Ca$h Munny, Sarabveer(VEER™)
65 "[UMC] Ultimate Mapchooser Core" (3.6.2) by Original:Steell, Updates:Powerlord (3.4.6-dev), Mr.Silence (3.6.2)
66 "Fun Commands" (1.9.0.6280) by AlliedModders LLC
67 "[UMC] Echo Nextmap" (3.6.2) by Steell
68 "AFK Manager" (4.3.0) by Rothgar
69 "Knife ghost error fix" (1.0.0) by Phoenix (˙·٠●Феникс●٠·˙)
70 "autodemo" (2.2.4) by mukunda
71 "Knife choice INTERFASE MONUL - Выбор ножа МОДУЛЬ ИНТЕРФЕЙСА" (1.1) by Phoenix - Феникс
72 "[UMC] Admin Menu" (3.6.2) by Steell
73 "[LR] Core" (v2.5.4.2) by RoadSide Romeo
74 "Prime Natives" (1.0.0) by Someone
75 "Sound Commands" (1.9.0.6280) by AlliedModders LLC
76 "Admin File Reader" (1.9.0.6280) by AlliedModders LLC
77 "[UMC] Vote Command" (3.6.2) by Steell
78 "ChangeTeamPlayer | Смена команды игроку" (1.0) by Drumanid
79 "Anti-Flood" (1.9.0.6280) by AlliedModders LLC
80 "Basic Commands" (1.9.0.6280) by AlliedModders LLC
81 "Basic Votes" (1.9.0.6280) by AlliedModders LLC
82 "Advanced c4 Countdown Timer" (1.5.0) by dalto, Panda
83 "[LR] Module - FakeRank" (v2.5.1) by RoadSide Romeo
84 "[LR] Module - Unusual Kills" (v2.5.4.2 F4) by Wend4r
85 "[LR] Module - ExStats Weapons" (v2.5.4) by RoadSide Romeo
86 "[LR] Module - VIP for TOP" (2.0) by Designed (Discord: .Designed#7985)
87 "[CS:GO] Admin Weapons Menu (rus)" (1.0.1) by Grey83
88 "Weapon Restrict" (1.2.0) by Phoenix (˙·٠●Феникс●٠·˙)
89 "[Keys] VIP" (1.3) by R1KO
90 "[Keys] Core" (1.4) by R1KO
91 "Material Admin" (0.7.7) by Material Admin Dev Team
92 "Basic Comm Control" (0.7.7) by AlliedModders LLC
93 "Admin Help" (1.9.0.6280) by AlliedModders LLC
94 "[Discord] SourceBans + SourceComms" (1.2.2) by CrazyHackGUT aka Kruzya
95 "[Discord] Core" (1.0.8) by CrazyHackGUT aka Kruzya
96 "[Discord] Simple Report System" (1.2.2) by CrazyHackGUT aka Kruzya
97 "Discord/DiscordTest.smx"
98 "Gloves" (1.6) by Phoenix (˙·٠●Феникс●٠·˙)
99 "Simple Chat Processor (Redux)" (1.1.5) by Simple Plugins, Mini
100 "CSGO Panorama Map Change Crashe Fixer" (1.0.6) by BOT Benson
101 "Basic Info Triggers" (1.9.0.6280) by AlliedModders LLC
102 "Special Team Balancer" (0.5.0) by AlmazON
103 "Game Description Override" (1.0.0) by Left
104 "SM Franug Hats" (3.3.3) by Franc1sco franug
105 "[CS:GO] ChatSpy" (1337) by ESK0
106 "Client Preferences" (1.9.0.6280) by AlliedModders LLC
107 "[UMC] End of Map Vote" (3.6.2) by Steell
108 "Token Auto Updater" (1.4) by Phoenix (˙·٠●Феникс●٠·˙)
<details>

**Comment by Silenci0** [comment]
As far  as the trigger spam, I do not know if it is normal or not, but I don't believe it is. So far, you've been the only one to report that, so it could be due to a server setting or something in the UMC configuration file (not the mapcycle file, but the configuration file itself). However, it should pick up if maxrounds are being used or not instead of round timer and, based on settings, it should create an endvote for whatever round you setup the plugin to run the vote for.

As far as the UMC map config, I noticed you are using workshop maps as well as stock maps. As far as I am aware, UMC has trouble with workshop maps at this time (it is something I'm currently looking into), so do you know if the maps that are having issues are the workshop maps or does stock also have the same issue as well?

**Comment by arestonelle** [comment]
I'm already notice to myself some time ago that with default maps (or if map downloaded to root server map folder) it's work fine. I'll test it out again with some certain conditions and reply back there.

It's very sad, cuz if i'll download workshop maps and copypaste them to the root folder it can work good. But all workshop maps hasn't radar...

**Comment by arestonelle** [comment]
Silence, i must very-very strong to apologize... Today i was pissed out, and disable UMC, download and enable MCE(exteded) and... I got the same problem! :\

So i will re-create server maybe, try add plugins one by one and experemental way find out which one causes this bug. 

I'm sorry again. Think that this issue can be closed right now.

**Comment by Silenci0** [comment]
There is no need to apologize. If the plugin is giving you trouble, feel free to uninstall. It is your server after all and you are the one who has to be happy with it. I used to run servers long ago, so I understand the struggle. :)

I will go ahead and close this issue as requested, but feel free to open a new thread if you choose to use UMC again. That said, I am letting you know now that UMC does have a problem with workshop maps at this time (or at least, many people have said so) and it is a problem I am working on when I have time to do so. Regardless, good luck with your server!

**Comment by MrBacks07** [comment]
I have the same problem which he has in 2019.

Someone know what's can be a solution?
