### ISSUE TITLE
Admin menu votes broken.

### ISSUE THREAD

**Issue by StrikerMan780** [Silenci0/UMC#2]
If you try to do a vote from the admin menu, it'll let you set up the vote, but once the vote starts, it cuts out when completed, not going anywhere (no map change, runoff, etc), and leaving a blank hud hint on your screen. If you try to RTV or trigger another vote, it says a vote is in progress, and gets permanently stuck that way unless you stop the "ghost" vote from the admin menu, or force a map change.

**Comment by Silenci0** [comment]
Thank you for letting me know. I shall look into this issue and update when I have resolved it. I am assuming this issue appears in TF2 much like the last issue reported, so I shall work on the plugin/test it there.

**Comment by Silenci0** [comment]
Thank you for reporting and sorry for the long wait. This issue has been resolved as of 3.6.2. Be sure to include the umc-adminmenu.smx and umc-core.smx modules. Closing issue.
