### ISSUE TITLE
umc nomination bug

### ISSUE THREAD

**Issue by Ayrton09** [Silenci0/UMC#6]
hello Silenci0 thanks for your working on UMC and SMAC really appreciated.

plugins seems to works fine, except the nomination module, i have a multimod server if someone nominate for example a minigame map and the group vote won was surf, the vote will see like this example..

vote for your next map!
surf_1
surf_2
mg_nominated (or any nominated map)
surf_3
surf_4
surf_5

thanks.

**Comment by Ayrton09** [comment]
thanks for answer..

Are you using tiered/group voting?- yes my server is multimod and has mini games, surf, deathrun, etc.
yes i have umc playerlimits installed.
[umc_mapcycle.txt](https://github.com/Silenci0/UMC/files/2799647/umc_mapcycle.txt)

[ultimate-mapchooser.txt](https://github.com/Silenci0/UMC/files/2799650/ultimate-mapchooser.txt)
[umc-nominate.txt](https://github.com/Silenci0/UMC/files/2799651/umc-nominate.txt)

umc configs uploaded in .txt because github not accepting .cfg files.

**Comment by Ayrton09** [comment]
[SM] Listing 63 plugins:
  01 "[CSS/CS:GO] AbNeR ResetScore" (1.5fix) by AbNeR_CSS
  02 "Admin File Reader" (1.9.0.6274) by AlliedModders LLC
  03 "Admin Help" (1.9.0.6274) by AlliedModders LLC
  04 "Admin List" (1.2) by Fredd
  05 "Admin Menu" (1.9.0.6274) by AlliedModders LLC
  06 "Advertisements" (2.0.2) by Tsunami
  07 "Anti-Flood" (1.9.0.6274) by AlliedModders LLC
  08 "Basic Ban Commands" (1.9.0.6274) by AlliedModders LLC
  09 "Basic Chat" (1.9.0.6274) by AlliedModders LLC
  10 "Basic Comm Control" (1.9.0.6274) by AlliedModders LLC
  11 "Basic Commands" (1.9.0.6274) by AlliedModders LLC
  12 "Basic Info Triggers" (1.9.0.6274) by AlliedModders LLC
  13 "Basic Votes" (1.9.0.6274) by AlliedModders LLC
  14 "Connect Announce" (1.8) by Arg!
  15 "Client Preferences" (1.9.0.6274) by AlliedModders LLC
  16 "[CS:GO] bug fix - bot add jointeam" (1.0) by Bacardi
  17 "CS:GO Movement Unlocker" (1.0) by Peace-Maker
  18 "[CSGO] Team Limit Bypass" (1.1) by Zephyrus
  19 "DR.API HIGH PING KICKER" (1.0.1) by Dr. Api
  20 "Ent-Control" (0.0.1.81) by LeGone
  21 "Force AllTalk" (1.1) by Nickelony
  22 "Fun Commands" (1.9.0.6274) by AlliedModders LLC
  23 "Fun Votes" (1.9.0.6274) by AlliedModders LLC
  24 "fix map give usp" (1.1) by Phoenix - Феникс
  25 "[Any] Improved Join Team Messages" (1.3.0.3) by Oshizu, ReFlexPoison (Helped many times with plugin) and Allower
  26 "[CS:GO] Damage Text" (1.6) by Kento, Kxnrl, IT-KiLLER, root88
  27 "RankMe" (3.0.3.Kento.30.2) by lok1, Scooby, Kento, pracc, Kxnrl, CrazyHackGUT
  28 "Map configs" (1.3) by Berni
  29 "Map end cvars reset" (2.1) by St00ne
  30 "Nextmap" (1.9.0.6274) by AlliedModders LLC
  31 "Noblock for players and nades" (1.0) by tommie113
  32 "PermaMute" (0.1) by Ryan "FLOOR_MASTER" Mannion (Editors: R1KO and XERXES AT)
  33 "Player Commands" (1.9.0.6274) by AlliedModders LLC
  34 "Quake Sounds v3" (3.5.0) by Spartan_C001
  35 "Reserved Slots" (1.9.0.6274) by AlliedModders LLC
  36 "Player Respawn" (1.6) by Rogue
  37 "Self-Mute Intelligence" (1.5.2) by IT-KiLLER and (Otokiru, edit 93x, Accelerator)
  38 "Sound Commands" (1.9.0.6274) by AlliedModders LLC
  39 "Stop Map Music" (1.0.0) by GoD-Tony [Fixed by The Count]
  40 "[UMC] Admin Menu" (3.6.2) by Steell
  41 "[UMC] Ultimate Mapchooser Core" (3.6.2) by Original:Steell, Updates:Powerlord (3.4.6-dev), Mr.Silence (3.6.2)
  42 "[UMC] Echo Nextmap" (3.6.2) by Steell
  43 "[UMC] End of Map Vote Warnings" (3.6.2) by Steell
  44 "[UMC] End of Map Vote" (3.6.2) by Steell
  45 "[UMC] Map Commands" (3.6.2) by Steell
  46 "[UMC] Nominations" (3.6.2) by Steell
  47 "[UMC] Player Limits" (3.6.2) by Steell
  48 "[UMC] Post-Played Exclusion" (3.6.2) by Sazpaimon and Steell
  49 "[UMC] Rock The Vote" (3.6.2) by Steell
  50 "[UMC] Time Limits" (3.6.2) by Steell
  51 "[UMC] Vote Command" (3.6.2) by Steell
  52 "VoiceAnnounceEx" (2.2.0) by Franc1sco franug, Mini and GoD-Tony
  53 "Weapon Restrict" (4.0.0-b7) by Dr!fter
  54 "AFK Manager" (4.3.0) by Rothgar
  55 "SourceMod Anti-Cheat" (0.8.6.3) by SMAC Development Team (original), Mr. Silence (updated)
  56 "SMAC Aimbot Detector" (0.8.6.3) by SMAC Development Team (original), Mr. Silence (updated)
  57 "SMAC AutoTrigger Detector" (0.8.6.3) by SMAC Development Team (original), Mr. Silence (updated)
  58 "SMAC Client Protection" (0.8.6.3) by SMAC Development Team (original), Mr. Silence (updated)
  59 "SMAC Command Monitor" (0.8.6.3) by SMAC Development Team (original), Mr. Silence (updated)
  60 "SMAC ConVar Checker" (0.8.6.3) by SMAC Development Team (original), Mr. Silence (updated)
  61 "SMAC Rcon Locker" (0.8.6.3) by SMAC Development Team (original), Mr. Silence (updated)
  62 "SMAC Anti-Speedhack" (0.8.6.3) by SMAC Development Team (original), Mr. Silence (updated)
  63 "SMAC Spinhack Detector" (0.8.6.3) by SMAC Development Team (original), Mr. Silence (updated)

**Comment by Silenci0** [comment]
After looking into this further, I believe this is a bug/conflict with the voting and nominations plugins themselves for UMC and what is attempted to be done with them when displaying a vote to decide the next map. 

So when a map is nominated by a player, it will either be displayed at the top or bottom of the voting list (depending on the configuration setting of sm_umc_mapnom_display in ultimate-mapchooser.cfg). What I believe is happening is that the map group being voted will list all its maps and the plugin will add the nominated maps into the list as well, which causes the bug to look as described, at least, this is the case if the nomination display setting was set to 1 and not 0. However, even if the setting was set to 0, the map would still appear, but at the end of the voting list, so the nominated map, regardless of the setting, will always appear in the vote. So the conflict is between the ability to nominate maps and the voting plugins (endvote and rtv). 

I'm not sure there is a proper solution to this that can resolve the problem code-wise. The best solution, assuming you'd rather users vote on a group first and then on a map from that particular group, would be to remove the ability to nominate maps and have users either RTV or wait until the end of a round to vote. This would remove the conflict and ensure the desired outcome of only listing maps from the group voted upon. If you still need nominations for that server, try setting the nomination display to 0 which would display all nominated maps at the bottom of the map voting list (though it would still appear in the vote).

**Comment by Ayrton09** [comment]
thanks silence! i will try it, If I had a pbug or something I will let you know.

**Comment by Silenci0** [comment]
I will go ahead and close this if there is nothing further for this issue. Please let me know if anything else comes up. Thank you!
